export const categories = [
  { id: 'all', name: 'الكل', icon: '🥩' },
  { id: 'lamb', name: 'الذبائح البلدية', icon: '🐑', image: '/images/naimi-realistic.png' },
  { id: 'kilo', name: 'لحم بالكيلو', icon: '⚖️', image: '/images/meat-cuts.jpg' },
  { id: 'veggies', name: 'خضروات وفواكه', icon: '🍎', image: '/images/fresh-produce.jpg' },
  { id: 'kashta', name: 'كشتة ولحم', icon: '⛺', image: '/images/bbq-prep.jpg' },
];

export const products = [
  // الذبائح البلدية (Saudi Livestock) - 7 Variants as requested
  {
    id: 1,
    name: "نعيمي كبير",
    category: "lamb",
    price: 1850,
    unit: "ذبيحة",
    image: "https://images.unsplash.com/photo-1545468202-39649bdf5f0f?auto=format&fit=crop&q=80&w=800",
    description: "خروف نعيمي بلدي فاخر، حجم كبير، تربية مزارعنا الخاصة. الوزن التقريبي 22-25 كجم.",
    badge: "وفر المال",
    size: "كبير",
    weight: "22-25 كجم",
    isFeatured: true,
  },
  {
    id: 2,
    name: "نعيمي وسط",
    category: "lamb",
    price: 1650,
    unit: "ذبيحة",
    image: "https://images.unsplash.com/photo-1511044391307-299307ba74bb?auto=format&fit=crop&q=80&w=800",
    description: "خروف نعيمي بلدي، حجم وسط، جودة عالية. الوزن التقريبي 18-21 كجم.",
    badge: "جديد",
    size: "وسط",
    weight: "18-21 كجم",
    isFeatured: true,
  },
  {
    id: 3,
    name: "نعيمي صغير",
    category: "lamb",
    price: 1450,
    unit: "ذبيحة",
    image: "https://images.unsplash.com/photo-1484557918186-73482bc4327e?auto=format&fit=crop&q=80&w=800",
    description: "خروف نعيمي بلدي، حجم صغير، لحم طري. الوزن التقريبي 15-17 كجم.",
    badge: "وفر المال",
    size: "صغير",
    weight: "15-17 كجم",
    isFeatured: true,
  },
  {
    id: 4,
    name: "نعيمي لباني",
    category: "lamb",
    price: 1300,
    unit: "ذبيحة",
    image: "https://images.unsplash.com/photo-1484557052118-f32bd25b45b5?auto=format&fit=crop&q=80&w=800",
    description: "نعيمي لباني صغير جداً، مثالي للمناسبات الخاصة. الوزن التقريبي 12-14 كجم.",
    badge: "جديد",
    size: "لباني",
    weight: "12-14 كجم",
    isFeatured: false,
  },
  {
    id: 5,
    name: "تيس بلدي",
    category: "lamb",
    price: 1100,
    unit: "ذبيحة",
    image: "https://images.unsplash.com/photo-1524024973431-2ad916746881?auto=format&fit=crop&q=80&w=800",
    description: "تيس بلدي لحم طيب وشهي، صغير الحجم. الوزن التقريبي 10-12 كجم.",
    badge: "وفر المال",
    size: "صغير",
    weight: "10-12 كجم",
    isFeatured: false,
  },
  {
    id: 6,
    name: "حري فاخر",
    category: "lamb",
    price: 1550,
    unit: "ذبيحة",
    image: "https://images.unsplash.com/photo-1484557918186-73482bc4327e?auto=format&fit=crop&q=80&w=800",
    description: "خروف حري بلدي فاخر، من أجود أنواع اللحوم. الوزن التقريبي 20-23 كجم.",
    badge: "جديد",
    size: "كبير",
    weight: "20-23 كجم",
    isFeatured: false,
  },
  {
    id: 7,
    name: "جذع فاخر (تميمة)",
    category: "lamb",
    price: 1700,
    unit: "ذبيحة",
    image: "https://images.unsplash.com/photo-1511044391307-299307ba74bb?auto=format&fit=crop&q=80&w=800",
    description: "جذع فاخر مثالي للتميمة والعقيقة. الوزن التقريبي 19-22 كجم.",
    badge: "وفر المال",
    size: "جذع",
    weight: "19-22 كجم",
    isFeatured: false,
  },

  // لحم بالكيلو (Meat by Kilo) - 6 items
  {
    id: 8,
    name: "كيلو لحم غنم نعيمي",
    category: "kilo",
    price: 95,
    unit: "كجم",
    image: "https://images.unsplash.com/photo-1607623814075-e512199b008b?auto=format&fit=crop&q=80&w=800",
    description: "لحم غنم نعيمي طازج مقطع حسب الطلب.",
    badge: "جديد",
    isFeatured: true,
  },
  {
    id: 9,
    name: "كيلو لحم حاشي",
    category: "kilo",
    price: 75,
    unit: "كجم",
    image: "https://images.unsplash.com/photo-1551028150-64b9f398f678?auto=format&fit=crop&q=80&w=800",
    description: "لحم حاشي بلدي طازج يومياً.",
    badge: "وفر المال",
    isFeatured: false,
  },
  {
    id: 10,
    name: "كيلو لحم عجل بلدي",
    category: "kilo",
    price: 85,
    unit: "كجم",
    image: "https://images.unsplash.com/photo-1546248136-3d63d9115d9b?auto=format&fit=crop&q=80&w=800",
    description: "لحم عجل بلدي صغير، قليل الدسم.",
    badge: "جديد",
    isFeatured: false,
  },
  {
    id: 11,
    name: "مفروم غنم نعيمي",
    category: "kilo",
    price: 90,
    unit: "كجم",
    image: "https://images.unsplash.com/photo-1588168333991-ad3631664bb1?auto=format&fit=crop&q=80&w=800",
    description: "مفروم طازج من لحم الغنم النعيمي.",
    badge: "وفر المال",
    isFeatured: false,
  },
  {
    id: 12,
    name: "كيلو ريش غنم",
    category: "kilo",
    price: 120,
    unit: "كجم",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=800",
    description: "ريش غنم نعيمي طازجة للشواء.",
    badge: "جديد",
    isFeatured: true,
  },
  {
    id: 13,
    name: "كيلو مقادم",
    category: "kilo",
    price: 40,
    unit: "كجم",
    image: "https://images.unsplash.com/photo-1607623814075-e512199b008b?auto=format&fit=crop&q=80&w=800",
    description: "مقادم بلدي طازجة ونظيفة.",
    badge: "جديد",
    isFeatured: false,
  },

  // خضروات وفواكه (Vegetables & Fruits) - 6 items
  {
    id: 14,
    name: "صندوق طماطم بلدي",
    category: "veggies",
    price: 25,
    unit: "صندوق",
    image: "https://images.unsplash.com/photo-1518977676601-b53f02ac6d31?auto=format&fit=crop&q=80&w=800",
    description: "طماطم بلدية طازجة من مزارعنا.",
    badge: "وفر المال",
    isFeatured: false,
  },
  {
    id: 15,
    name: "كيس بصل",
    category: "veggies",
    price: 15,
    unit: "كيس",
    image: "https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&q=80&w=800",
    description: "بصل أحمر طازج عالي الجودة.",
    badge: "جديد",
    isFeatured: false,
  },
  {
    id: 16,
    name: "كيس بطاطس",
    category: "veggies",
    price: 20,
    unit: "كيس",
    image: "https://images.unsplash.com/photo-1518977676601-b53f02ac6d31?auto=format&fit=crop&q=80&w=800",
    description: "بطاطس بلدية ممتازة للقلي والطبخ.",
    badge: "وفر المال",
    isFeatured: false,
  },
  {
    id: 17,
    name: "خيار طازج (كيلو)",
    category: "veggies",
    price: 8,
    unit: "كجم",
    image: "https://images.unsplash.com/photo-1449339043598-793221151336?auto=format&fit=crop&q=80&w=800",
    description: "خيار طازج ومقرمش يومياً.",
    badge: "جديد",
    isFeatured: false,
  },
  {
    id: 18,
    name: "كرتون برتقال عصير",
    category: "veggies",
    price: 35,
    unit: "كرتون",
    image: "https://images.unsplash.com/photo-1557800636-894a64c1696f?auto=format&fit=crop&q=80&w=800",
    description: "برتقال طازج مثالي للعصير.",
    badge: "جديد",
    isFeatured: false,
  },
  {
    id: 19,
    name: "سلة فواكه مشكلة",
    category: "veggies",
    price: 65,
    unit: "سلة",
    image: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=800",
    description: "تشكيلة مختارة من الفواكه الموسمية.",
    badge: "وفر المال",
    isFeatured: false,
  },

  // كشتة ولحم (Camping Packages) - 6 items
  {
    id: 20,
    name: "صندوق الشواء العائلي",
    category: "kashta",
    price: 450,
    unit: "بكس",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=800",
    description: "بكس متكامل للشواء يحتوي على لحم نعيمي، دجاج، وخضروات.",
    badge: "وفر المال",
    isFeatured: true,
  },
  {
    id: 21,
    name: "بكس المشاوي الملكي",
    category: "kashta",
    price: 950,
    unit: "بكس",
    image: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&q=80&w=800",
    description: "عرض ملكي يحتوي على تشكيلة فاخرة من اللحوم والريش.",
    badge: "جديد",
    isFeatured: true,
  },
  {
    id: 22,
    name: "عدة الكشتة المتكاملة",
    category: "kashta",
    price: 250,
    unit: "طقم",
    image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&q=80&w=800",
    description: "فحم، مواقد، وأدوات الشواء الضرورية.",
    badge: "جديد",
    isFeatured: false,
  },
  {
    id: 23,
    name: "بكس البرجر المنزلي",
    category: "kashta",
    price: 180,
    unit: "بكس",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=800",
    description: "لحم مفروم طازج مع خبز البرجر والصوصات.",
    badge: "وفر المال",
    isFeatured: false,
  },
  {
    id: 24,
    name: "صندوق السهرة والسمر",
    category: "kashta",
    price: 120,
    unit: "صندوق",
    image: "https://images.unsplash.com/photo-1534464539014-998c5641772b?auto=format&fit=crop&q=80&w=800",
    description: "شاي، قهوة، تمر، ومكسرات فاخرة.",
    badge: "جديد",
    isFeatured: false,
  },
  {
    id: 25,
    name: "بكس الريش والمقبلات",
    category: "kashta",
    price: 320,
    unit: "بكس",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=800",
    description: "ريش غنم متبلة مع مجموعة من المقبلات.",
    badge: "جديد",
    isFeatured: false,
  }
];

export const heroImage = "/images/naimi-realistic.png";
